### ISSUE TITLE
As for help with putting ThreadedGSM class to another class

### ISSUE THREAD

**Issue by Piotr66** [neta540/ArduinoThreadedGSM#2]
I have to ask you a favor. I want to “hide” Your class ThreadedGSM in my own class. I made a try, but not everything is working. It’s look like:

gms_c.h
------------
#include "ThreadedGSM.h" // Author: Neta Yahav
#include "PduEncoder.h"  // Author: Ludovic Laurent

class gsm_c {
    private:
        //ThreadedGSM *SIM800L;
        void signal(ThreadedGSM& modem, ThreadedGSM::SignalLevel& Signal);

    public:
        // ----- Constructor -----          
        //gsm_c();
        gsm_c(HardwareSerial& port);        
        void init();
        void sendAlarmSMS();
        void gsm_loop();        
};

gms_c.cpp
------------
#include "gsm_c.h"

//gsm_c::gsm_c() {
//	// nothing
//	init();
//}

gsm_c::gsm_c(HardwareSerial& port) {
    init();
}

void gsm_c::init() {
    Serial1.begin(115200);
    //SIM800L->begin();
    SIM800L.begin();

    //SIM800L->setInterval(ThreadedGSM::INTERVAL_SIGNAL, 60000);
    SIM800L.setInterval(ThreadedGSM::INTERVAL_SIGNAL, 60000);

    SIM800L.setHandlers({
	.signal = signal,
	.clock = NULL,
	.incoming = NULL,
	.ready = NULL,
	.outgoing = NULL,
	.power = NULL
    });     
}

void gsm_c::signal(ThreadedGSM& modem, ThreadedGSM::SignalLevel& Signal) {
	Serial.print("Modem signal: Dbm:");
	Serial.print(Signal.Dbm);
	Serial.print(" value: ");
	Serial.println(Signal.Value);
}

void gsm_c::sendAlarmSMS() {
    PduEncoder PDU;
    String sms, encodedPDU;
                        
    PDU.setSMSCnumber("+XXXXXXXXXXX");
    PDU.setSender("+XXXXXXXXXXX");
    
    sms  = "Piec - ALARM - Temp: ";
    sms += currentTemp;
    sms += "\rStan pompy: ";
   
    switch(stanPompy) {
        case 0: sms +="OFF"; break;
        case 1: sms +="ON"; break;
        default: sms +="???"; break;
    }

    sms += "\rTryb pracy pompy: ";
    switch(trybPompy) {
        case 0: sms += "AUTO"; break;
        case 1: sms += "ON"; break;
        case 2: sms += "OFF"; break;
        default: sms += "???"; break;
    }

    PDU.setText(sms);
    encodedPDU = PDU.encode();

    //SIM800L->sendSMS(encodedPDU);
    SIM800L.sendSMS(encodedPDU);
}

void gsm_c::gsm_loop() {
	//SIM800L->loop();
	SIM800L.loop();
}

The problem is with the SIM800L.setHandlers function. When I put there

    SIM800L.setHandlers({
	.signal = NULL,
	.clock = NULL,
	.incoming = NULL,
	.ready = NULL,
	.outgoing = NULL,
	.power = NULL
    });     

Sending SMS and loop() is working, but I need signal. If I change .signal = NULL to .signal = signal I’m getting this error:

src\gsm_c.cpp:50:3: error: no matching function for call to 'ThreadedGSM::setHandlers(<brace-enclosed initializer list>)'
In file included from include/gsm_c.h:10:0,
                 from src\gsm_c.cpp:1:
src/ThreadedGSM.h:186:7: note: candidate: void ThreadedGSM::setHandlers(ThreadedGSM::conf)
  void setHandlers(conf config)
       ^
src/ThreadedGSM.h:186:7: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'ThreadedGSM::conf'

How should I pass config to ThreadedGSM object in this situation? Could You help mi with that please? My knowledge of C++ is rather at basic level. :(

**Comment by neta540** [comment]
Right, it will not work, because the handlers must not be a part of a class.
It is a callback, you get the callback outside of your class(es).
What you can do however (as a suggestion) is run your class gsm_c as a singleton in your project, so you can then know how to return the call data into that class. Within the global "signal" function you call that singleton instance to execute your inner "signal" function.

First you will need to modify constructor to take no arguments, instead, set the port in the init function `HardwareSerial& port` in another function. Also make gsm_c class a singleton as follows so its instance could be referenced from our global function. Anytime you'll use gsm_c within the program, just call `gsm_c::getInstance()` to get its instance.  It's just a normal singleton design pattern.
If you want to learn more about singleton you can read here: https://sourcemaking.com/design_patterns/singleton/cpp/1

`gms_c.cpp` will then need to be setting the port to in a separate procedure. It will also require setHandlers to be used from "outside", so we can plug the **global** signal handler. `onSignal` will be the **inner** signal handler.

```c++
gsm_c* gsm_c::instance = 0;

gsm_c* gsm_c::getInstance() {
  if (instance == 0) {
    instance = new gsm_c();
  }

  return instance;
}

void gsm_c::init(HardwareSerial& port) {
  // whatever you do with the port like saving it to a variable
  // you can use that variable later, at any time you need to use the port.
}

void gsm_c::onSignal(ThreadedGSM& modem, ThreadedGSM::SignalLevel& Signal) {
  // whatever you want to do with the signal
}

void gsm_c::setHandlers(ThreadedGSM::conf config) {
  SIM800L.setHandlers(config);
}
```

`main.cpp` will need to create a new gsm_c instance, that will be done the first time calling `getInstance()`. Once it is called, the next `getInstance()` calls will not create a new instances but instead will re-use the previous instance created.

```c++
void setup() {
  gsm_c::getInstance()->init(Serial1);
  // set the handlers here so the global function will be used
  // as required by the library
  gsm_c::getInstance()->setHandlers({
    .signal = signal,
    .clock = NULL,
    .incoming = NULL,
    .ready = NULL,
    .outgoing = NULL,
    .power = NULL
  }); 
}

void signal(ThreadedGSM& modem, ThreadedGSM::SignalLevel& Signal)
{
  // return the signal to the class handling it
  gsm_c::getInstance()->onSignal(modem, Signal);
}
```


I haven't tried any of this but it should work.

**Comment by Piotr66** [comment]
> I haven't tried any of this but it should work.

And guess what? It’s W O R K I N G !
Thank You very much. 😊
